{{- if .Values.mongodb.enabled }}
{{- if .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: releasea-mongodb-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
  {{- if .Values.mongodb.persistence.storageClassName }}
  storageClassName: {{ .Values.mongodb.persistence.storageClassName | quote }}
  {{- end }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: releasea-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: releasea-mongodb
  template:
    metadata:
      labels:
        app: releasea-mongodb
      {{- with .Values.mongodb.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.mongodb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mongodb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mongodb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image | quote }}
          ports:
            - containerPort: {{ .Values.mongodb.service.port }}
          {{- if .Values.mongodb.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /data/db
          {{- end }}
          {{- with .Values.mongodb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.mongodb.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: releasea-mongodb-data
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: releasea-mongodb
spec:
  selector:
    app: releasea-mongodb
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}
{{- end }}
