{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: releasea-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: releasea-rabbitmq
  template:
    metadata:
      labels:
        app: releasea-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image | quote }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.rabbitmq.auth.username | quote }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.rabbitmq.auth.password | quote }}
          ports:
            - containerPort: {{ .Values.rabbitmq.service.amqpPort }}
            - containerPort: {{ .Values.rabbitmq.service.managementPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: releasea-rabbitmq
spec:
  selector:
    app: releasea-rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.amqpPort }}
      targetPort: {{ .Values.rabbitmq.service.amqpPort }}
    - name: management
      port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: {{ .Values.rabbitmq.service.managementPort }}
{{- end }}
